ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#obj-(CONFIG_MTK_N2DM_SUPPORT) = n2dm.o
obj-y := n2dm.o
n2dm-objs := n2dm_common.o n2dm_acc.o
