ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#obj-(CONFIG_MTK_LIS3DH_SUPPORT) = lis3dh.o
obj-y := lps22hb.o
lps22hb-objs := lps22hb_common.o lps22hb_baro.o
