ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/baroerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-y := lps22hh.o
lps22hh-objs := lps22hh_common.o lps22hh_baro.o
