ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/humidity/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/temperature/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-y	:=  hts221.o

