ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/tilt_detector_sensor/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y := lsm6ds3.o
lsm6ds3-objs := lsm6ds3_common.o lsm6ds3_acc.o lsm6ds3_gyro.o lsm6ds3_step.o
