ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/tilt_detector_sensor/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-y := lis2ds12.o
lis2ds12-objs := lis2ds12_common.o lis2ds12_acc.o lis2ds12_step.o
