ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/tilt_detector_sensor/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y := lis2ds12.o
lis2ds12-objs := lis2ds12_common.o lis2ds12_acc.o lis2ds12_step.o
