ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/tilt_detector_sensor/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y := lsm6ds3trc.o
lsm6ds3trc-objs := lsm6ds3trc_common.o lsm6ds3trc_acc.o lsm6ds3trc_gyro.o lsm6ds3trc_step.o
