ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/step_counter/
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/tilt_detector_sensor/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-y := lsm6ds3c.o
lsm6ds3c-objs := lsm6ds3c_common.o lsm6ds3c_acc.o lsm6ds3c_gyro.o lsm6ds3c_step.o
