ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
#obj-(CONFIG_MTK_LIS3DH_SUPPORT) = lis3dh.o
obj-y := lps25hb.o
lps25hb-objs := lps25hb_common.o lps25hb_baro.o
